apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tn-openbsw-meet
namePrefix: meet-

buildMetadata: [originAnnotations]

resources:
  - manifests/configmap-redis.yaml
  - manifests/deployment-backend.yaml
  - manifests/deployment-celery.yaml
  - manifests/deployment-frontend.yaml
  - manifests/deployment-mailcatcher.yaml
  - manifests/deployment-minio.yaml
  - manifests/deployment-redis.yaml
  - manifests/deployment-summary.yaml
  - manifests/ingress-admin.yaml
  - manifests/ingress-backend.yaml
  - manifests/postgresql-cluster.yaml
  - manifests/pvc-minio.yaml
  - manifests/secret-backend.yaml
  - manifests/secret-minio.yaml
  - manifests/secret-postgres-super.yaml
  - manifests/secret-postgres.yaml
  - manifests/secret-summary.yaml
  - manifests/service-backend.yaml
  - manifests/service-mailcatcher.yaml
  - manifests/service-frontend.yaml
  - manifests/service-minio.yaml
  - manifests/service-redis.yaml
  - manifests/service-summary.yaml
