apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: livekit-turn-cert
  namespace: tn-openbsw-meet
spec:
  dnsNames:
    - turn.meet.la-suite.apps.digilab.network
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: livekit-turn-cert
  usages:
    - digital signature
    - key encipherment
