apiVersion: v1
data:
  config.yaml: |
    keys:
      APIpFVsiPdJFukz: eEZzEY4hmiiK3TgNtc0qEqqUErkAwmL30tehlChq1NeB
    log_level: debug
    logging:
      level: debug
    port: 7880
    redis:
      address: meet-svc-redis:6379
    rtc:
      tcp_port: 7881
      port_range_start: 50000
      port_range_end: 60000
      use_external_ip: true
      enable_loopback_candidate: false
    turn:
      enabled: true
      domain: turn.meet.la-suite.apps.digilab.network
      tls_port: 443
      udp_port: 443
      external_tls: false
kind: ConfigMap
metadata:
  name: livekit-livekit-server
