apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-egress
data:
  config.yaml: |
    enable_chrome_sandbox: true
    health_port: 8080
    insecure: true
    log_level: debug
    prometheus_port: 9090
    redis:
      address: meet-svc-redis:6379
    s3:
      bucket: meet-media-storage
      endpoint: http://meet-svc-minio:9000
      force_path_style: true
      region: local
    ws_url: ws://meet-svc-livekit:80
