apiVersion: v1
kind: ConfigMap
metadata:
  name: livekit-livekit-server
data:
  config.yaml: |
    keys:
      ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
    log_level: debug
    port: 7880
    redis:
      address: meet-svc-redis.tn-openbsw-meet.svc.cluster.local:6379
    rtc:
      port_range_end: 60000
      port_range_start: 50000
      tcp_port: 7881
      use_external_ip: false
    turn:
      domain: turn.la-suite.apps.digilab.network
      enabled: true
      loadBalancerAnnotations: {}
      udp_port: 443
