apiVersion: v1
data:
  config.yaml: |
    keys:
      ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
    log_level: debug
    logging:
      level: debug
    port: 7880
    redis:
      address: meet-svc-redis:6379
    rtc:
      port_range_end: 60000
      port_range_start: 50000
      tcp_port: 7881
      use_external_ip: true
    turn:
      enabled: true
      domain: turn.meet.la-suite.apps.digilab.network
      udp_port: 3478
      tls_port: 5349
      external_tls: false
kind: ConfigMap
metadata:
  name: livekit-livekit-server
