apiVersion: v1
data:
  config.yaml: |
    keys:
      ${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}
    log_level: debug
    logging:
      level: debug
    port: 7880
    redis:
      address: meet-svc-redis:6379
    rtc:
      tcp_port: 7881
      udp_port: 7882
      use_external_ip: false
    turn:
      enabled: true
      domain: 57.153.140.146
      tls_port: 443
      udp_port: 3478
      external_tls: false
kind: ConfigMap
metadata:
  name: livekit-livekit-server
