apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-egress
  labels:
    app: livekit-egress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-egress
  template:
    metadata:
      labels:
        app: livekit-egress
    spec:
      serviceAccountName: default
      securityContext: {}
      terminationGracePeriodSeconds: 18000
      containers:
        - name: egress
          securityContext: {}
          image: livekit/egress:v1.8.4
          imagePullPolicy: IfNotPresent
          env:
            - name: EGRESS_CONFIG_BODY
              valueFrom:
                configMapKeyRef:
                  name: livekit-egress
                  key: config.yaml
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: sec-minio
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: sec-minio
          ports:
            - name: health
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: health
          readinessProbe:
            httpGet:
              path: /
              port: health
          resources: {}
