apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-celery
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: meet
      app.kubernetes.io/instance: meet
      app.kubernetes.io/component: celery
  template:
    metadata:
      labels:
        app.kubernetes.io/name: meet
        app.kubernetes.io/instance: meet
        app.kubernetes.io/component: celery
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-az1pool1-29662286-vmss000001
      shareProcessNamespace: false
      containers:
        - name: meet
          image: lasuite/meet-summary:v0.1.12
          imagePullPolicy: Always
          command:
            - celery
            - -A
            - summary.core.celery_worker
            - worker
            - --pool=solo
            - --loglevel=info
          env:
            - name: APP_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: APP_API_TOKEN
                  name: summary
            - name: APP_NAME
              value: summary-microservice
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: sec-minio
            - name: AWS_S3_ENDPOINT_URL
              value: svc-minio
            - name: AWS_S3_REGION_NAME
              value: local
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: sec-minio
            - name: AWS_STORAGE_BUCKET_NAME
              value: meet-media-storage
            - name: CELERY_BROKER_URL
              value: redis://meet-svc-redis:6379
            - name: CELERY_RESULT_BACKEND
              value: redis://meet-svc-redis:6379
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  key: OPENAI_API_KEY
                  name: summary
            - name: OPENAI_ASR_MODEL
              value: whisper-1
            - name: OPENAI_BASE_URL
              value: https://api.openai.com/v1/
            - name: OPENAI_LLM_MODEL
              value: gpt-4o-mini
            - name: SENTRY_IS_ENABLED
              value: "false"
            - name: WEBHOOK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: WEBHOOK_API_TOKEN
                  name: summary
            - name: WEBHOOK_URL
              value: https://docs.la-suite.apps.digilab.network/api/v1.0/documents/create-for-owner/
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
      volumes:
