apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-livekit-server
  labels:
    app: livekit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      labels:
        app: livekit-server
    spec:
      terminationGracePeriodSeconds: 18000
      initContainers:
        - name: init-config
          image: dibi/envsubst:1
          command:
            [
              "sh",
              "-c",
              "envsubst < /etc/livekit-template/config.yaml > /etc/livekit/config.yaml",
            ]
          env:
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
          volumeMounts:
            - name: config-volume
              mountPath: /etc/livekit-template
            - name: workdir
              mountPath: /etc/livekit
      containers:
        - name: livekit-server
          securityContext: {}
          image: "livekit/livekit-server:v1.8.3"
          imagePullPolicy: IfNotPresent
          args:
            ["--disable-strict-config", "--config", "/etc/livekit/config.yaml"]
          env:
            - name: LIVEKIT_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: livekit-livekit-server
                  key: config.yaml
            - name: LIVEKIT_TURN_CERT
              value: /etc/lkcert/tls.crt
            - name: LIVEKIT_TURN_KEY
              value: /etc/lkcert/tls.key
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: rtc-tcp
              containerPort: 7881
              protocol: TCP
            - name: turn
              containerPort: 3478
              protocol: TCP
            - name: turn-tls
              containerPort: 5349
              protocol: TCP
            - name: turn-udp
              containerPort: 3478
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/livekit-template
            - name: workdir
              mountPath: /etc/livekit
            - name: lkturncert
              mountPath: /etc/lkcert
              readOnly: true
      volumes:
        - name: workdir
          emptyDir: {}
        - name: config-volume
          configMap:
            name: livekit-livekit-server
        - name: lkturncert
          secret:
            secretName: livekit-turn-cert
