apiVersion: apps/v1
kind: Deployment
metadata:
  name: meet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meet-backend
  template:
    metadata:
      labels:
        app: meet-backend
    spec:
      securityContext:
        runAsUser: 0
      containers:
        - name: meet
          command:
            [
              "gunicorn",
              "-c",
              "/usr/local/etc/gunicorn/meet.py",
              "meet.wsgi:application",
              "--reload",
            ]
          image: lasuite/meet-backend:v0.1.15
          imagePullPolicy: Always
          env:
            - name: CORS_ALLOW_ALL_ORIGINS
              value: "true"
            - name: ALLOW_UNREGISTERED_ROOMS
              value: "false"
            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: minio_root_user
                  name: sec-minio
            - name: AWS_S3_ENDPOINT_URL
              value: http://meet-svc-minio:9000
            - name: AWS_S3_REGION_NAME
              value: local
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: minio_root_password
                  name: sec-minio
            - name: AWS_STORAGE_BUCKET_NAME
              value: meet-media-storage
            - name: CELERY_BROKER_URL
              value: redis://meet-svc-redis:6379/1
            - name: DB_HOST
              value: meet-cluster-db-rw
            - name: DB_NAME
              value: meet
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: sec-postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  key: username
                  name: sec-postgres
            - name: DJANGO_ALLOWED_HOSTS
              value: "meet.la-suite.apps.digilab.network"
            - name: DJANGO_CSRF_TRUSTED_ORIGINS
              value: https://meet.la-suite.apps.digilab.network/
            - name: DJANGO_EMAIL_HOST
              value: meet-svc-mailcatcher
            - name: DJANGO_EMAIL_PORT
              value: "1025"
            - name: DJANGO_EMAIL_USE_SSL
              value: "False"
            - name: DJANGO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SECRET_KEY
                  name: sec-backend
            - name: DJANGO_SILENCED_SYSTEM_CHECKS
              value: security.W004, security.W008
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SUPERUSER_EMAIL
                  name: sec-backend
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DJANGO_SUPERUSER_PASSWORD
                  name: sec-backend
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
            # - name: LIVEKIT_API_URL
            #   value: https://meet-6b0kiy8h.livekit.cloud
            - name: LIVEKIT_API_URL
              value: https://livekit.meet.la-suite.apps.digilab.network
            - name: LOGIN_REDIRECT_URL
              value: https://meet.la-suite.apps.digilab.network
            - name: LOGIN_REDIRECT_URL_FAILURE
              value: https://meet.la-suite.apps.digilab.network
            - name: LOGOUT_REDIRECT_URL
              value: https://meet.la-suite.apps.digilab.network
            - name: OIDC_OP_AUTHORIZATION_ENDPOINT
              value: https://id.la-suite.apps.digilab.network/realms/lasuite/protocol/openid-connect/auth
            - name: OIDC_OP_JWKS_ENDPOINT
              value: https://id.la-suite.apps.digilab.network/realms/lasuite/protocol/openid-connect/certs
            - name: OIDC_OP_LOGOUT_ENDPOINT
              value: https://id.la-suite.apps.digilab.network/realms/lasuite/protocol/openid-connect/logout
            - name: OIDC_OP_TOKEN_ENDPOINT
              value: https://id.la-suite.apps.digilab.network/realms/lasuite/protocol/openid-connect/token
            - name: OIDC_OP_USER_ENDPOINT
              value: https://id.la-suite.apps.digilab.network/realms/lasuite/protocol/openid-connect/userinfo
            - name: OIDC_REDIRECT_ALLOWED_HOSTS
              value: https://meet.la-suite.apps.digilab.network
            - name: OIDC_USERINFO_FULLNAME_FIELDS
              value: name
            - name: OIDC_RP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: OIDC_RP_CLIENT_ID
                  name: sec-backend
            - name: OIDC_RP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: OIDC_RP_CLIENT_SECRET
                  name: sec-backend
            - name: OIDC_RP_SCOPES
              value: openid email profile
            - name: OIDC_RP_SIGN_ALGO
              value: RS256
            - name: RECORDING_ENABLE
              value: "true"
            - name: RECORDING_VERIFY_SSL
              value: "false"
            - name: RECORDING_STORAGE_EVENT_ENABLE
              value: "true"
            - name: RECORDING_STORAGE_EVENT_TOKEN
              valueFrom:
                secretKeyRef:
                  key: RECORDING_STORAGE_EVENT_TOKEN
                  name: sec-backend
            - name: REDIS_URL
              value: redis://meet-svc-redis:6379
            - name: "DJANGO_CONFIGURATION"
              value: "Production"
            - name: "RESOURCE_DEFAULT_IS_PUBLIC"
              value: "true"
            - name: SUMMARY_SERVICE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  key: APP_API_TOKEN
                  name: summary
            - name: SUMMARY_SERVICE_ENDPOINT
              value: http://meet-svc-meet-summary:8000/api/v1/tasks/
            - name: DJANGO_SETTINGS_MODULE
              value: meet.settings
            - name: FRONTEND_SUPPORT
              value: ""
            - name: STORAGES_STATICFILES_BACKEND
              value: django.contrib.staticfiles.storage.StaticFilesStorage
            - name: RECORDING_WORKER_CLASSES
              value: "{'transcript': 'core.recording.worker.services.AudioCompositeEgressService'}"
            - name: RESOURCE_DEFAULT_ACCESS_LEVEL
              value: restricted
          resources:
            requests:
              cpu: 60m
              memory: 512Mi
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /__heartbeat__
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /__lbheartbeat__
              port: 8000
            initialDelaySeconds: 30
            timeoutSeconds: 1
          volumeMounts:
      volumes:
