apiVersion: apps/v1
kind: Deployment
metadata:
  name: livekit-livekit-server
  labels:
    app: livekit-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: livekit-server
  template:
    metadata:
      annotations:
        linkerd.io/inject: disabled
        sidecar.istio.io/inject: "false"
      labels:
        app: livekit-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: aks-az1pool1-29662286-vmss000001
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      terminationGracePeriodSeconds: 18000
      initContainers:
        - name: init-config
          image: dibi/envsubst:1
          command:
            [
              "sh",
              "-c",
              "envsubst < /etc/livekit-template/config.yaml > /etc/livekit/config.yaml",
            ]
          entrypoint: [""]
          env:
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
          volumeMounts:
            - name: config-volume
              mountPath: /etc/livekit-template
            - name: workdir
              mountPath: /etc/livekit
      containers:
        - name: livekit-server
          securityContext: {}
          image: livekit/livekit-server:v1.8.0
          imagePullPolicy: IfNotPresent
          args: [--disable-strict-config, --config, /etc/livekit/config.yaml]
          env:
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_KEY
                  name: sec-backend
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  key: LIVEKIT_API_SECRET
                  name: sec-backend
          ports:
            - name: http
              containerPort: 7880
              protocol: TCP
            - name: rtc-tcp
              containerPort: 7881
              hostPort: 7881
              protocol: TCP
            - name: turn-udp
              containerPort: 443
              hostPort: 443
              protocol: UDP
            - name: turn-tcp
              containerPort: 443
              hostPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config-volume
              mountPath: /etc/livekit-template
            - name: workdir
              mountPath: /etc/livekit
      volumes:
        - name: workdir
          emptyDir: {}
        - name: config-volume
          configMap:
            name: livekit-livekit-server
