kind: Ingress
metadata:
  name: ing-livekit
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
apiVersion: networking.k8s.io/v1
spec:
  rules:
    - host: livekit.meet.la-suite.apps.digilab.network
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: svc-livekit
                port:
                  number: 80
  tls:
    - hosts:
        - livekit.meet.la-suite.apps.digilab.network
      secretName: livekit-cert
