apiVersion: v1
kind: Secret
metadata:
  name: summary
stringData:
  APP_API_TOKEN: ENC[AES256_GCM,data:FZM7MTXzCYTVxlyEDY1jJTN0BTkZLMow,iv:cLCK1EABDdG1I2aWKbP7Zln7aR05nVo3yDHrSfTc0CI=,tag:THPxw7v4YD5Ggtjn/QxMtw==,type:str]
  OPENAI_API_KEY: ENC[AES256_GCM,data:htkgESr4K+t+e7QYioRdbAYDcwIhA3LEobUg000idTmaHJD/5YoC5yKVR9EtUE1zj7Ig/uQsDDQZr2FWUYGpf99VoguC+QcweymnpMjmTzG+R+XoE0QSSLjPf4AkDe4eUtQoKuqWxVdKeI2Ukfv+NvVZbd4PQPz4+QysmgRJjANmT+MLaSsF+2F6C6oB0/G0Z4mMAv4s9f0hdtf8goqGmDGjHdA=,iv:I2rJhm+UVY8SxclQ0DEilPLcZ5VMg+bounrt+si5EdE=,tag:HYV+DOOlW+pwTmY0GOvFSw==,type:str]
  WEBHOOK_API_TOKEN: ENC[AES256_GCM,data:YGp6WBUostVCom78dnGuh1Flk8ne4gkwSQ==,iv:b7xraEqHAdbYta4/KBusqJSRcGfAOOxt3ufRAo00LNA=,tag:whTohMPjyR3mP0juW8Swrw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18ut09wsuwf4pusrhywlu9nu3nzvz040m26h4yghhhtvqm88an3zssvsz9m
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRWNVR0hsYmdxanI1aFVo
        ZEcwKzRsbHpiVmJMakpqMGdTZWM0SWUyK0NFCjArN1ExdGJ1MzZGMTgzVTVHYWh3
        ZEpIbk5iREZUNTNaOUhuWEx4WkhpdTgKLS0tIG9Cb3BiSjQ3VXhqamVVWit0OUJz
        M2pCTjVNbmdqMnRBbU1QQ2NOdXlHblEKo5UbKmF1/j80xQ4VsEelYQYnyrEc0ZZZ
        cMKYNkeMK5YrFUpK4K7jw8HVx4OwdnJIj8ii+69O4vB/tCD+yPC9qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-01-13T21:11:02Z"
  mac: ENC[AES256_GCM,data:lZjs53sTPCqHvC5rbbBNFCdyEDuSTo56R76i48UYy+07Nt1fbyYIu+UyLcTuGar4FzeK2mIihZkdO7uHOnnZ5Wqsgs+uiA8xl8rgqWWy9toWim8JSn+/C6KT+9e5G0KbropLpYLshfwVVUQ28nse4ztginnH7VxSqu8hZohXlWA=,iv:5dDk/V0Qc5EpROEJiVIPTpjwBNW5BH+krbMQ6RmnQbc=,tag:0eT+7PmH8vYunrndOt1fXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
