apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-turn
spec:
  ports:
    - port: 443
      targetPort: turn-tcp
      protocol: TCP
      name: turn-tcp
  selector:
    app: livekit-server
  type: LoadBalancer
