apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-server-turn
spec:
  type: LoadBalancer
  ports:
    - name: turn-tls-5349
      protocol: TCP
      port: 5349
      targetPort: turn-tls
    - name: turn-tls-443
      protocol: TCP
      port: 443
      targetPort: turn-tls
  selector:
    app: livekit-server
---
apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-server-turn-udp
spec:
  type: LoadBalancer
  ports:
  - name: turn-udp
    protocol: UDP
    port: 3478
    targetPort: 3478
  selector:
    app: livekit-server
