apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-server
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: livekit-server
  type: ClusterIP
