apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-server-turn
spec:
  type: LoadBalancer
  ports:
    - name: stun-turn-udp
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: stun-turn-tcp
      protocol: TCP
      port: 5349
      targetPort: 5349
    - name: media
      protocol: UDP
      port: 50000
      targetPort: 50000
  selector:
    app: livekit-server