apiVersion: v1
kind: Service
metadata:
  name: svc-livekit-server-turn
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "turn.meet.la-suite.apps.digilab.network"
spec:
  type: LoadBalancer
  ports:
    - name: stun-turn-udp
      protocol: UDP
      port: 3478
      targetPort: 3478
    - name: stun-turn-tcp
      protocol: TCP
      port: 443
      targetPort: 443
    - name: media-tcp
      protocol: TCP
      port: 7881
      targetPort: 7881
    - name: media-udp
      protocol: UDP
      port: 7882
      targetPort: 7882
  selector:
    app: livekit-server