apiVersion: v1
kind: Service
metadata:
  name: livekit-livekit-server-turn
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: 3478
      protocol: TCP
  selector:
    app: meet-livekit-server
