apiVersion: v1
kind: Service
metadata:
  name: svc-livekit
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
    - name: rtc-tcp
      port: 7881
      protocol: TCP
      targetPort: rtc-tcp

  selector:
    app: livekit-server
  type: LoadBalancer
